spring.application.name=productApp

#json\uC5D0\uC11C null \uC81C\uC678
spring.jackson.default-property-inclusion=non_null

###\uB85C\uCEEC \uC0AC\uC6A9 ###
spring.profiles.active=local

server.port=22722