spring.application.name=productApp

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=productuser
spring.datasource.password=wantedproduct!23
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#json ?? null? ? ??
spring.jackson.default-property-inclusion=non_null


server.port=22722